site_name: B&R Jenkins Helper
nav:
  - Home: index.md
plugins:
  - search
  - mermaid2
theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - content.code.copy
markdown_extensions:
    - toc:
        permalink:
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format